# Generated by Django 5.1.1 on 2024-11-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('price', models.IntegerField()),
                ('expdata', models.DateField()),
            ],
        ),
    ]
